name: "enhancer"
backend: "python"
max_batch_size: 32

instance_group [
  {
    kind: KIND_GPU
  }
]

# dynamic_batching {
#   preferred_batch_size: [ 4, 8 ]
#   max_queue_delay_microseconds: 100
# }


input [
    {
        name: "input",
        data_type: TYPE_FP32,
        dims: [-1],
    }
]
output [
    {
        name: "output",
        data_type: TYPE_FP32,
        dims: [-1],
    }
]
